export type WorldCountry = {
  iso2: string;
  labelEn: string;
  labelAr: string;
};

export function flagUrl(iso2: string, size: 40 | 80 | 160 = 80) {
  return `https://flagcdn.com/w${size}/${iso2.toLowerCase()}.png`;
}

export function countryIsoFromLabelAr(labelAr: string) {
  return WORLD_COUNTRIES.find((c) => c.labelAr === labelAr)?.iso2 ?? null;
}

export function domainLogo(domain: string) {
  return `https://www.google.com/s2/favicons?domain=${encodeURIComponent(domain)}&sz=128`;
}

export function mediaUrl(src: string | null | undefined, apiOrigin: string) {
  if (!src) return null;
  if (/^(https?:|blob:|data:)/i.test(src)) return src;
  const base = apiOrigin.replace(/\/$/, '');
  return src.startsWith('/') ? `${base}${src}` : `${base}/${src}`;
}

/** Full ISO country list for admin country picker. */
export const WORLD_COUNTRIES: WorldCountry[] = [
  { iso2: 'AF', labelEn: 'Afghanistan', labelAr: 'أفغانستان' },
  { iso2: 'AL', labelEn: 'Albania', labelAr: 'ألبانيا' },
  { iso2: 'DZ', labelEn: 'Algeria', labelAr: 'الجزائر' },
  { iso2: 'AD', labelEn: 'Andorra', labelAr: 'أندورا' },
  { iso2: 'AO', labelEn: 'Angola', labelAr: 'أنغولا' },
  { iso2: 'AG', labelEn: 'Antigua and Barbuda', labelAr: 'أنتيغوا وباربودا' },
  { iso2: 'AR', labelEn: 'Argentina', labelAr: 'الأرجنتين' },
  { iso2: 'AM', labelEn: 'Armenia', labelAr: 'أرمينيا' },
  { iso2: 'AU', labelEn: 'Australia', labelAr: 'أستراليا' },
  { iso2: 'AT', labelEn: 'Austria', labelAr: 'النمسا' },
  { iso2: 'AZ', labelEn: 'Azerbaijan', labelAr: 'أذربيجان' },
  { iso2: 'BS', labelEn: 'Bahamas', labelAr: 'الباهاما' },
  { iso2: 'BH', labelEn: 'Bahrain', labelAr: 'البحرين' },
  { iso2: 'BD', labelEn: 'Bangladesh', labelAr: 'بنغلاديش' },
  { iso2: 'BB', labelEn: 'Barbados', labelAr: 'باربادوس' },
  { iso2: 'BY', labelEn: 'Belarus', labelAr: 'بيلاروس' },
  { iso2: 'BE', labelEn: 'Belgium', labelAr: 'بلجيكا' },
  { iso2: 'BZ', labelEn: 'Belize', labelAr: 'بليز' },
  { iso2: 'BJ', labelEn: 'Benin', labelAr: 'بنين' },
  { iso2: 'BT', labelEn: 'Bhutan', labelAr: 'بوتان' },
  { iso2: 'BO', labelEn: 'Bolivia', labelAr: 'بوليفيا' },
  { iso2: 'BA', labelEn: 'Bosnia and Herzegovina', labelAr: 'البوسنة والهرسك' },
  { iso2: 'BW', labelEn: 'Botswana', labelAr: 'بوتسوانا' },
  { iso2: 'BR', labelEn: 'Brazil', labelAr: 'البرازيل' },
  { iso2: 'BN', labelEn: 'Brunei', labelAr: 'بروناي' },
  { iso2: 'BG', labelEn: 'Bulgaria', labelAr: 'بلغاريا' },
  { iso2: 'BF', labelEn: 'Burkina Faso', labelAr: 'بوركينا فاسو' },
  { iso2: 'BI', labelEn: 'Burundi', labelAr: 'بوروندي' },
  { iso2: 'CV', labelEn: 'Cabo Verde', labelAr: 'الرأس الأخضر' },
  { iso2: 'KH', labelEn: 'Cambodia', labelAr: 'كمبوديا' },
  { iso2: 'CM', labelEn: 'Cameroon', labelAr: 'الكاميرون' },
  { iso2: 'CA', labelEn: 'Canada', labelAr: 'كندا' },
  { iso2: 'CF', labelEn: 'Central African Republic', labelAr: 'جمهورية أفريقيا الوسطى' },
  { iso2: 'TD', labelEn: 'Chad', labelAr: 'تشاد' },
  { iso2: 'CL', labelEn: 'Chile', labelAr: 'تشيلي' },
  { iso2: 'CN', labelEn: 'China', labelAr: 'الصين' },
  { iso2: 'CO', labelEn: 'Colombia', labelAr: 'كولومبيا' },
  { iso2: 'KM', labelEn: 'Comoros', labelAr: 'جزر القمر' },
  { iso2: 'CG', labelEn: 'Congo', labelAr: 'الكونغو' },
  { iso2: 'CD', labelEn: 'Congo (DRC)', labelAr: 'الكونغو الديمقراطية' },
  { iso2: 'CR', labelEn: 'Costa Rica', labelAr: 'كوستاريكا' },
  { iso2: 'CI', labelEn: 'Côte d’Ivoire', labelAr: 'ساحل العاج' },
  { iso2: 'HR', labelEn: 'Croatia', labelAr: 'كرواتيا' },
  { iso2: 'CU', labelEn: 'Cuba', labelAr: 'كوبا' },
  { iso2: 'CY', labelEn: 'Cyprus', labelAr: 'قبرص' },
  { iso2: 'CZ', labelEn: 'Czechia', labelAr: 'التشيك' },
  { iso2: 'DK', labelEn: 'Denmark', labelAr: 'الدنمارك' },
  { iso2: 'DJ', labelEn: 'Djibouti', labelAr: 'جيبوتي' },
  { iso2: 'DM', labelEn: 'Dominica', labelAr: 'دومينيكا' },
  { iso2: 'DO', labelEn: 'Dominican Republic', labelAr: 'جمهورية الدومينيكان' },
  { iso2: 'EC', labelEn: 'Ecuador', labelAr: 'الإكوادور' },
  { iso2: 'EG', labelEn: 'Egypt', labelAr: 'مصر' },
  { iso2: 'SV', labelEn: 'El Salvador', labelAr: 'السلفادور' },
  { iso2: 'GQ', labelEn: 'Equatorial Guinea', labelAr: 'غينيا الاستوائية' },
  { iso2: 'ER', labelEn: 'Eritrea', labelAr: 'إريتريا' },
  { iso2: 'EE', labelEn: 'Estonia', labelAr: 'إستونيا' },
  { iso2: 'SZ', labelEn: 'Eswatini', labelAr: 'إسواتيني' },
  { iso2: 'ET', labelEn: 'Ethiopia', labelAr: 'إثيوبيا' },
  { iso2: 'FJ', labelEn: 'Fiji', labelAr: 'فيجي' },
  { iso2: 'FI', labelEn: 'Finland', labelAr: 'فنلندا' },
  { iso2: 'FR', labelEn: 'France', labelAr: 'فرنسا' },
  { iso2: 'GA', labelEn: 'Gabon', labelAr: 'الغابون' },
  { iso2: 'GM', labelEn: 'Gambia', labelAr: 'غامبيا' },
  { iso2: 'GE', labelEn: 'Georgia', labelAr: 'جورجيا' },
  { iso2: 'DE', labelEn: 'Germany', labelAr: 'ألمانيا' },
  { iso2: 'GH', labelEn: 'Ghana', labelAr: 'غانا' },
  { iso2: 'GR', labelEn: 'Greece', labelAr: 'اليونان' },
  { iso2: 'GD', labelEn: 'Grenada', labelAr: 'غرينادا' },
  { iso2: 'GT', labelEn: 'Guatemala', labelAr: 'غواتيمالا' },
  { iso2: 'GN', labelEn: 'Guinea', labelAr: 'غينيا' },
  { iso2: 'GW', labelEn: 'Guinea-Bissau', labelAr: 'غينيا بيساو' },
  { iso2: 'GY', labelEn: 'Guyana', labelAr: 'غيانا' },
  { iso2: 'HT', labelEn: 'Haiti', labelAr: 'هايتي' },
  { iso2: 'HN', labelEn: 'Honduras', labelAr: 'هندوراس' },
  { iso2: 'HU', labelEn: 'Hungary', labelAr: 'المجر' },
  { iso2: 'IS', labelEn: 'Iceland', labelAr: 'آيسلندا' },
  { iso2: 'IN', labelEn: 'India', labelAr: 'الهند' },
  { iso2: 'ID', labelEn: 'Indonesia', labelAr: 'إندونيسيا' },
  { iso2: 'IR', labelEn: 'Iran', labelAr: 'إيران' },
  { iso2: 'IQ', labelEn: 'Iraq', labelAr: 'العراق' },
  { iso2: 'IE', labelEn: 'Ireland', labelAr: 'أيرلندا' },
  { iso2: 'IT', labelEn: 'Italy', labelAr: 'إيطاليا' },
  { iso2: 'JM', labelEn: 'Jamaica', labelAr: 'جامايكا' },
  { iso2: 'JP', labelEn: 'Japan', labelAr: 'اليابان' },
  { iso2: 'JO', labelEn: 'Jordan', labelAr: 'الأردن' },
  { iso2: 'KZ', labelEn: 'Kazakhstan', labelAr: 'كازاخستان' },
  { iso2: 'KE', labelEn: 'Kenya', labelAr: 'كينيا' },
  { iso2: 'KI', labelEn: 'Kiribati', labelAr: 'كيريباتي' },
  { iso2: 'KW', labelEn: 'Kuwait', labelAr: 'الكويت' },
  { iso2: 'KG', labelEn: 'Kyrgyzstan', labelAr: 'قيرغيزستان' },
  { iso2: 'LA', labelEn: 'Laos', labelAr: 'لاوس' },
  { iso2: 'LV', labelEn: 'Latvia', labelAr: 'لاتفيا' },
  { iso2: 'LB', labelEn: 'Lebanon', labelAr: 'لبنان' },
  { iso2: 'LS', labelEn: 'Lesotho', labelAr: 'ليسوتو' },
  { iso2: 'LR', labelEn: 'Liberia', labelAr: 'ليبيريا' },
  { iso2: 'LY', labelEn: 'Libya', labelAr: 'ليبيا' },
  { iso2: 'LI', labelEn: 'Liechtenstein', labelAr: 'ليختنشتاين' },
  { iso2: 'LT', labelEn: 'Lithuania', labelAr: 'ليتوانيا' },
  { iso2: 'LU', labelEn: 'Luxembourg', labelAr: 'لوكسمبورغ' },
  { iso2: 'MG', labelEn: 'Madagascar', labelAr: 'مدغشقر' },
  { iso2: 'MW', labelEn: 'Malawi', labelAr: 'ملاوي' },
  { iso2: 'MY', labelEn: 'Malaysia', labelAr: 'ماليزيا' },
  { iso2: 'MV', labelEn: 'Maldives', labelAr: 'المالديف' },
  { iso2: 'ML', labelEn: 'Mali', labelAr: 'مالي' },
  { iso2: 'MT', labelEn: 'Malta', labelAr: 'مالطا' },
  { iso2: 'MH', labelEn: 'Marshall Islands', labelAr: 'جزر مارشال' },
  { iso2: 'MR', labelEn: 'Mauritania', labelAr: 'موريتانيا' },
  { iso2: 'MU', labelEn: 'Mauritius', labelAr: 'موريشيوس' },
  { iso2: 'MX', labelEn: 'Mexico', labelAr: 'المكسيك' },
  { iso2: 'FM', labelEn: 'Micronesia', labelAr: 'ميكرونيسيا' },
  { iso2: 'MD', labelEn: 'Moldova', labelAr: 'مولدوفا' },
  { iso2: 'MC', labelEn: 'Monaco', labelAr: 'موناكو' },
  { iso2: 'MN', labelEn: 'Mongolia', labelAr: 'منغوليا' },
  { iso2: 'ME', labelEn: 'Montenegro', labelAr: 'الجبل الأسود' },
  { iso2: 'MA', labelEn: 'Morocco', labelAr: 'المغرب' },
  { iso2: 'MZ', labelEn: 'Mozambique', labelAr: 'موزمبيق' },
  { iso2: 'MM', labelEn: 'Myanmar', labelAr: 'ميانمار' },
  { iso2: 'NA', labelEn: 'Namibia', labelAr: 'ناميبيا' },
  { iso2: 'NR', labelEn: 'Nauru', labelAr: 'ناورو' },
  { iso2: 'NP', labelEn: 'Nepal', labelAr: 'نيبال' },
  { iso2: 'NL', labelEn: 'Netherlands', labelAr: 'هولندا' },
  { iso2: 'NZ', labelEn: 'New Zealand', labelAr: 'نيوزيلندا' },
  { iso2: 'NI', labelEn: 'Nicaragua', labelAr: 'نيكاراغوا' },
  { iso2: 'NE', labelEn: 'Niger', labelAr: 'النيجر' },
  { iso2: 'NG', labelEn: 'Nigeria', labelAr: 'نيجيريا' },
  { iso2: 'KP', labelEn: 'North Korea', labelAr: 'كوريا الشمالية' },
  { iso2: 'MK', labelEn: 'North Macedonia', labelAr: 'مقدونيا الشمالية' },
  { iso2: 'NO', labelEn: 'Norway', labelAr: 'النرويج' },
  { iso2: 'OM', labelEn: 'Oman', labelAr: 'عُمان' },
  { iso2: 'PK', labelEn: 'Pakistan', labelAr: 'باكستان' },
  { iso2: 'PW', labelEn: 'Palau', labelAr: 'بالاو' },
  { iso2: 'PS', labelEn: 'Palestine', labelAr: 'فلسطين' },
  { iso2: 'PA', labelEn: 'Panama', labelAr: 'بنما' },
  { iso2: 'PG', labelEn: 'Papua New Guinea', labelAr: 'بابوا غينيا الجديدة' },
  { iso2: 'PY', labelEn: 'Paraguay', labelAr: 'باراغواي' },
  { iso2: 'PE', labelEn: 'Peru', labelAr: 'بيرو' },
  { iso2: 'PH', labelEn: 'Philippines', labelAr: 'الفلبين' },
  { iso2: 'PL', labelEn: 'Poland', labelAr: 'بولندا' },
  { iso2: 'PT', labelEn: 'Portugal', labelAr: 'البرتغال' },
  { iso2: 'QA', labelEn: 'Qatar', labelAr: 'قطر' },
  { iso2: 'RO', labelEn: 'Romania', labelAr: 'رومانيا' },
  { iso2: 'RU', labelEn: 'Russia', labelAr: 'روسيا' },
  { iso2: 'RW', labelEn: 'Rwanda', labelAr: 'رواندا' },
  { iso2: 'KN', labelEn: 'Saint Kitts and Nevis', labelAr: 'سانت كيتس ونيفيس' },
  { iso2: 'LC', labelEn: 'Saint Lucia', labelAr: 'سانت لوسيا' },
  { iso2: 'VC', labelEn: 'Saint Vincent and the Grenadines', labelAr: 'سانت فنسنت' },
  { iso2: 'WS', labelEn: 'Samoa', labelAr: 'ساموا' },
  { iso2: 'SM', labelEn: 'San Marino', labelAr: 'سان مارينو' },
  { iso2: 'ST', labelEn: 'Sao Tome and Principe', labelAr: 'ساو تومي وبرينسيب' },
  { iso2: 'SA', labelEn: 'Saudi Arabia', labelAr: 'السعودية' },
  { iso2: 'SN', labelEn: 'Senegal', labelAr: 'السنغال' },
  { iso2: 'RS', labelEn: 'Serbia', labelAr: 'صربيا' },
  { iso2: 'SC', labelEn: 'Seychelles', labelAr: 'سيشل' },
  { iso2: 'SL', labelEn: 'Sierra Leone', labelAr: 'سيراليون' },
  { iso2: 'SG', labelEn: 'Singapore', labelAr: 'سنغافورة' },
  { iso2: 'SK', labelEn: 'Slovakia', labelAr: 'سلوفاكيا' },
  { iso2: 'SI', labelEn: 'Slovenia', labelAr: 'سلوفينيا' },
  { iso2: 'SB', labelEn: 'Solomon Islands', labelAr: 'جزر سليمان' },
  { iso2: 'SO', labelEn: 'Somalia', labelAr: 'الصومال' },
  { iso2: 'ZA', labelEn: 'South Africa', labelAr: 'جنوب أفريقيا' },
  { iso2: 'KR', labelEn: 'South Korea', labelAr: 'كوريا الجنوبية' },
  { iso2: 'SS', labelEn: 'South Sudan', labelAr: 'جنوب السودان' },
  { iso2: 'ES', labelEn: 'Spain', labelAr: 'إسبانيا' },
  { iso2: 'LK', labelEn: 'Sri Lanka', labelAr: 'سريلانكا' },
  { iso2: 'SD', labelEn: 'Sudan', labelAr: 'السودان' },
  { iso2: 'SR', labelEn: 'Suriname', labelAr: 'سورينام' },
  { iso2: 'SE', labelEn: 'Sweden', labelAr: 'السويد' },
  { iso2: 'CH', labelEn: 'Switzerland', labelAr: 'سويسرا' },
  { iso2: 'SY', labelEn: 'Syria', labelAr: 'سوريا' },
  { iso2: 'TW', labelEn: 'Taiwan', labelAr: 'تايوان' },
  { iso2: 'TJ', labelEn: 'Tajikistan', labelAr: 'طاجيكستان' },
  { iso2: 'TZ', labelEn: 'Tanzania', labelAr: 'تنزانيا' },
  { iso2: 'TH', labelEn: 'Thailand', labelAr: 'تايلاند' },
  { iso2: 'TL', labelEn: 'Timor-Leste', labelAr: 'تيمور الشرقية' },
  { iso2: 'TG', labelEn: 'Togo', labelAr: 'توغو' },
  { iso2: 'TO', labelEn: 'Tonga', labelAr: 'تونغا' },
  { iso2: 'TT', labelEn: 'Trinidad and Tobago', labelAr: 'ترينيداد وتوباغو' },
  { iso2: 'TN', labelEn: 'Tunisia', labelAr: 'تونس' },
  { iso2: 'TR', labelEn: 'Turkey', labelAr: 'تركيا' },
  { iso2: 'TM', labelEn: 'Turkmenistan', labelAr: 'تركمانستان' },
  { iso2: 'TV', labelEn: 'Tuvalu', labelAr: 'توفالو' },
  { iso2: 'UG', labelEn: 'Uganda', labelAr: 'أوغندا' },
  { iso2: 'UA', labelEn: 'Ukraine', labelAr: 'أوكرانيا' },
  { iso2: 'AE', labelEn: 'United Arab Emirates', labelAr: 'الإمارات' },
  { iso2: 'GB', labelEn: 'United Kingdom', labelAr: 'بريطانيا' },
  { iso2: 'US', labelEn: 'United States', labelAr: 'أميركا' },
  { iso2: 'UY', labelEn: 'Uruguay', labelAr: 'أوروغواي' },
  { iso2: 'UZ', labelEn: 'Uzbekistan', labelAr: 'أوزبكستان' },
  { iso2: 'VU', labelEn: 'Vanuatu', labelAr: 'فانواتو' },
  { iso2: 'VA', labelEn: 'Vatican City', labelAr: 'الفاتيكان' },
  { iso2: 'VE', labelEn: 'Venezuela', labelAr: 'فنزويلا' },
  { iso2: 'VN', labelEn: 'Vietnam', labelAr: 'فيتنام' },
  { iso2: 'YE', labelEn: 'Yemen', labelAr: 'اليمن' },
  { iso2: 'ZM', labelEn: 'Zambia', labelAr: 'زامبيا' },
  { iso2: 'ZW', labelEn: 'Zimbabwe', labelAr: 'زيمبابوي' },
];
